#!/usr/bin/tclsh
package require Expect
package require Tclx
fconfigure stdin -blocking 1            ;#expect bug?

if  {$argc == 1} {
    set num [lindex $argv 0]
} else {
    puts -nonewline "which one (1-9, a-f)? "
    flush stdout
    gets stdin num
}

# increase delays for wireless devices
set delay 5
if {[string match -nocase *w* $num]} {
    set delay 10
}

# check for dx box copy
set host "sam$num"
set pass "shoot"
if {[string match -nocase dx* $num]} {
    puts -nonewline "Password for dx box? "
    system "stty -echo"
    flush stdout
    gets stdin pass
    system "stty echo"
    set host $num
}

system sed -i -e "s/^$host.*//" ~/.ssh/known_hosts
eval spawn scp RFmaster RFdump RFslave.new [glob *.arm] root@$host:~/
set timeout $delay
while 1 {
    expect {
        -re {.*word:.*} {
            send "$pass\r"
        }
        -re {.*yes/no.*} {
            send "yes\r"
        }
        eof {
            break
        }
    }
}
