#!/bin/sh

# overwrite start routine...
start () {
   # load network
   source /usr/bin/load_network

   # load modules
   load_modules "target_user_interface.ko mover=0" \
                "target_battery.ko minvoltval=12" \
                "target_hit_poll.ko line=0" \
                "target_generic_output.ko has_muzzle=1 has_moon=1 has_phi=1" \
                "target_lifter_infantry.ko" \
                "lifter.ko"

   # start the default programs
   def_progs

   # start fasit client
   fasit_conn -S -F -l $lport -p $cport -i $ip -vv -k &
}

# leave default stop routine
