#!/bin/sh

# overwrite start routine...
start () {
   # load network
   source /usr/bin/load_network

   # load modules
   load_modules "target_user_interface.ko mover=0" \
                "target_battery.ko minvoltval=12" \
                "target_hit_poll.ko line=1" \
                "target_generic_output.ko" \
                "target_lifter_armor.ko" \
                "lifter.ko"

   # start fasit client
   fasit_conn -S -l $lport -p $cport -i $ip &
}

# leave default stop routine
