#!/bin/sh

# overwrite start routine...
start () {
   # load network
   source /usr/bin/load_network

   matb=$(has_mat_battery)
   matm=$(has_mat_mover)
   matr=$(has_mat_reverse)
   if [ "$matb" == "" ] ; then                       
      matb=48                                         
   fi 
   if [ "$matm" == "" ] ; then                       
      matm=1                                         
   fi
   if [ "$matr" == "" ] ; then                       
      matr=0                                         
   fi

   # load modules
   load_modules "target_user_interface.ko mover=1" \
                "target_battery.ko minvoltval=$matb" \
                "target_mover_generic.ko mover_type=$matm reverse=$matr" \
                "target_generic_output.ko" \
                "mover.ko"

   # start default programs
   def_progs

   # start fasit client
   fasit_conn -M -l $lport -p $cport -i $ip -vv -k &
}

# leave default stop routine
