#!/bin/sh

# overwrite start routine...
start () {
   # load network
   source /usr/bin/load_network

   mitb = $(has_mit_battery)
   mitm = $(has_mit_mover)
   mitr = $(has_mit_reverse)
   if [ "$mitb" == "" ] ; then                       
      mitb=24                                         
   fi 
   if [ "$mitm" == "" ] ; then                       
      mitm=0                                         
   fi
   if [ "$mitr" == "" ] ; then                       
      mitr=0                                         
   fi

   # load modules
   load_modules "target_user_interface.ko mover=1" \
                "target_battery.ko minvoltval=$mitb" \
                "target_mover_generic.ko mover_type=$mitm reverse=$mitr" \
                "target_generic_output.ko" \
                "mover.ko"

   # start default programs
   def_progs

   # start fasit client
   fasit_conn -M -l $lport -p $cport -i $ip -vv -k &
}

# leave default stop routine
