#!/bin/sh

# overwrite start routine...
start () {
   # load network
   source /usr/bin/load_network

   mitm=3
   mitb=$(has_mit_battery)
   mitr=$(has_mover_reverse)
   mitd=$(has_dock)
   mitds=$(has_dock_speed)
   mith=$(has_home)
   track=$(has_track_length)
   if [ "$mitb" == "" ] ; then
      mitb=12
   fi
   if [ "$mitr" != "0" ] && [ "$mitr" != "1" ] ; then
      mitr=0
   fi
   if [ "$mitd" == "" ] ; then
# Assume no dock
      mitd=2
   fi
   if [ "$mith" == "" ] ; then
# Assume home on left
      mith=0
   fi
   if [ "$track" == "" ] ; then
      track=10
   fi
   if [ "$mitds" == "" ] ; then
      matd=0
   fi

   # load modules
   load_modules "target_user_interface.ko mover=1" \
                "target_battery.ko minvoltval=$mitb shutdown_wait=3" \
                "target_mover_generic.ko mover_type=$mitm reverse=$mitr dock_loc=$mitd dock_inc=$mitds track_len=$track home_loc=$mith" \
                "target_generic_output.ko" \
                "mover.ko"

   # start default programs
   def_progs

   # start fasit client
   fasit_conn -M -l $lport -p $cport -i $ip -k &
}

# leave default stop routine
