#!/bin/sh

# overwrite start routine...
start () {
   # load network
   source /usr/bin/load_network

   # load modules
   load_modules "target_battery.ko minvoltval=12"

   # start the default programs
   def_progs
}

# overwrite stop routine...
stop () {
   # unload everything we loaded
   unload
}
