#!/bin/sh

# overwrite start routine...
start () {
   # load network
   source /usr/bin/load_network

   satb=$(has_sat_battery)
   thermx=$(has_thermalX)
   therm=$(has_thermal)
   msdh=$(has_msdh)
   if [ "$satb" == "" ] ; then
      satb=12
   fi
   if [ "$therm" == "" ] ; then                       
      therm=0                                         
   fi
   if [ "$thermx" == "" ] ; then                       
      thermx=0                                         
   fi
   if [ "$msdh" == "" ] ; then                       
      msdh=0                                         
   fi

   # load modules
   load_modules "target_user_interface.ko mover=0" \
                "target_battery.ko minvoltval=$satb shutdown_wait=10" \
                "target_hit_poll.ko line=0" \
                "target_generic_output.ko has_thermal=$therm has_thermalX=$thermx has_msdh=$msdh" \
                "target_lifter_armor.ko" \
                "lifter.ko"

   # start default programs
   def_progs

   # start fasit client
   fasit_conn -s -F -l $lport -p $cport -i $ip -k &
}

# leave default stop routine
