#!/bin/sh

# overwrite start routine...
start () {
   # load network
   source /usr/bin/load_network

   satb=$(has_sat_battery)
   thermx=$(has_thermalX)
   therm=$(has_thermal)
   msdh=$(has_msdh)
   satbes=$(has_bes_mode)
   thermp=$(has_thermal_pulse)
   htk=$(has_hits_to_kill)
   htb=$(has_hits_to_bob)
   if [ "$satb" == "" ] ; then
      satb=12
   fi
   if [ "$therm" == "" ] ; then                       
      therm=0                                         
   fi
   if [ "$thermx" == "" ] ; then                       
      thermx=0                                         
   fi
   if [ "$msdh" == "" ] ; then                       
      msdh=0                                         
   fi
   if [ "$satbes" == "" ] ; then                       
      satbes=0                                         
   fi
   if [ "$thermp" == "" ] ; then                       
      thermp=0                                         
   fi
   if [ "$htk" == "" ] ; then                       
      htk=1                                       
   fi
      if [ "$htb" == "" ] ; then                       
      htb=1                                       
   fi

   # load modules
   load_modules "eeprom_settings.ko" \
                "target_user_interface.ko mover=0" \
                "target_battery.ko minvoltval=$satb shutdown_wait=10 has_bes=$satbes" \
                "target_hit_poll.ko line=0 sens_mult=2" \
                "target_generic_output.ko has_thermal=$therm has_thermalX=$thermx has_msdh=$msdh has_bes=$satbes has_thm_pulse=$thermp" \
                "target_lifter_armor.ko" \
                "lifter.ko has_bes=$satbes has_thm_pulse=$thermp has_hits_to_kill=$htk has_hits_to_bob=$htb"

   # start default programs
   def_progs

   # start fasit client
   fasit_conn -s -F -l $lport -p $cport -i $ip -k &
}

# leave default stop routine
