#!/bin/sh

# overwrite start routine...
start () {
   # load network
   source /usr/bin/load_network

   satb=$(has_sat_battery)
   if [ "$satb" == "" ] ; then
      satb=12
   fi

   # load modules
   load_modules "target_user_interface.ko mover=0" \
                "target_battery.ko minvoltval=$satb" \
                "target_hit_poll.ko line=0" \
                "target_generic_output.ko" \
                "target_lifter_armor.ko" \
                "lifter.ko"

   # start default programs
   def_progs

   # start fasit client
   fasit_conn -S -l $lport -p $cport -i $ip -vv -k &
}

# leave default stop routine
