#!/bin/sh

# overwrite start routine...
start () {
   # load network
   source /usr/bin/load_network

   # load modules
   load_modules "target_user_interface.ko mover=0" \
                "target_battery.ko minvoltval=12" \
                "target_ses_interface.ko"

   # start default programs
   def_progs

   # start fasit client
   fasit_conn -E -l $lport -p $cport -i $ip -vvv &
}

# leave default stop routine
