#!/bin/sh

# overwrite start routine...
start () {
   # load network
   source /usr/bin/load_network

   mfs=$(has_muzzle)
   moon=$(has_moon)
   phi=$(has_phi)
   sitb=$(has_sit_battery)
   thermx=$(has_thermalX)
   therm=$(has_thermal)
   msdh=$(has_msdh)
   if [ "$mfs" == "" ] ; then                       
      mfs=1
   fi 
   if [ "$moon" == "" ] ; then                       
      moon=1
   fi
   if [ "$phi" == "" ] ; then                       
      phi=1
   fi
   if [ "$sitb" == "" ] ; then                       
      sitb=12                                         
   fi
   if [ "$therm" == "" ] ; then                       
      therm=0                                         
   fi
   if [ "$thermx" == "" ] ; then                       
      thermx=0                                         
   fi
   if [ "$msdh" == "" ] ; then                       
      msdh=0                                         
   fi
   # load modules
   load_modules "target_user_interface.ko mover=0" \
                "target_battery.ko minvoltval=$sitb shutdown_wait=1" \
                "target_hit_poll.ko line=0" \
                "target_generic_output.ko has_muzzle=$mfs has_moon=$moon has_phi=$phi has_thermal=$therm has_thermalX=$thermx has_msdh=$msdh" \
                "target_lifter_infantry.ko" \
                "lifter.ko"

   # start default programs
   def_progs

   # start fasit client
   fasit_conn -S -F -l $lport -p $cport -i $ip -k &
}

# leave default stop routine
