#!/bin/sh
#
# manage startup of drivers and python code

if ! [ -f /home/root/is_board ] ; then
    exit 0
fi

case "$1" in
    start)
        /usr/bin/$(cat /home/root/is_board) start &
        ;;
    stop)
        /usr/bin/$(cat /home/root/is_board) stop &
        ;;
    force-reload|restart)
        /usr/bin/$(cat /home/root/is_board) restart &
        ;;
    *)
        echo "Usage: /etc/init.d/networking {start|stop|restart|force-reload}"
        exit 1
        ;;
esac

