#!/bin/sh
#
# manage startup of drivers and python code

# set keepalive timeouts
sysctl -w \
 net.ipv4.tcp_keepalive_time=20 \
 net.ipv4.tcp_keepalive_intvl=10 \
 net.ipv4.tcp_keepalive_probes=3

is_board=$(/usr/bin/is_board)

case "$1" in
    start)
        /usr/bin/$is_board start &
        ;;
    stop)
        /usr/bin/$is_board stop &
        ;;
    force-reload|restart)
        /usr/bin/$is_board restart &
        ;;
    *)
        echo "Usage: /etc/init.d/start_up {start|stop|restart|force-reload}"
        exit 1
        ;;
esac

