#!/bin/sh

# overwrite start routine...
start () {
   # load network
   source /usr/bin/load_network

   # load modules
   load_modules "target_user_interface.ko mover=1" \
                "target_battery.ko minvoltval=48" \
                "target_mover_generic.ko mover_type=1 reverse=0" \
                "target_generic_output.ko" \
                "mover.ko"

   # start fasit client
   fasit_conn -M -l $lport -p $cport -i $ip &
}

# leave default stop routine
