#!/bin/sh

# kill userspace programs (will ignore ones not running)
killall -q -9 bcast_server
killall -q -9 radio_conv
killall -q -9 fasit_conn
killall -q -9 event_conn
killall -q -9 bit_button
killall -q -9 user_conn
killall -q -9 ping
# kill these more nicely
if ps aufx | grep -q "RF.*arm" ; then
   killall -q RFmaster.arm
   killall -q RFslave.arm
   killall -q RFslave.new.arm
   killall -q RFdump.arm
   killall -q slaveboss.arm
   sleep 2
   killall -q -9 RFmaster.arm
   killall -q -9 RFslave.arm
   killall -q -9 RFslave.new.arm
   killall -q -9 RFdump.arm
   killall -q -9 slaveboss.arm
fi

# recursive unload function
unmod () {
  # check if loaded
  loaded=$(lsmod | grep "$1 ")
  if [ -n "$loaded" ] ; then
     # find dependencies
     deps=$(lsmod | grep "$1 " | sed -e "s: *: :g" | cut -d' ' -f 5)
     if [ -n "$deps" ] ; then
        # unload dependencies
        for i in $(echo $deps | sed -e "s:,: :g") ; do
           # unload recursively
           unmod $i
        done
     fi
     # unload
     rmmod $1.ko
  fi
}

# unload kernel modules
cd /home/root
ls *.ko | while read i ; do
  mod=$(basename $i .ko)
  unmod $mod
done
