#!/usr/bin/tclsh
package require Expect
package require Tclx
fconfigure stdin -blocking 1            ;#expect bug?

if  {$argc == 1} {
    set num [lindex $argv 0]
} else {
    puts -nonewline "which one (1-9, a-f)? "
    flush stdout
    gets stdin num
}

# increase delays for wireless devices
set delay 5
if {[string match -nocase *w* $num]} {
    set delay 10
}

# grab the host by default via samXX or avahi host or cpe
set host sam$num
if {$num == {av}} {
    set f [open "|avahi-resolve-host-name -n server.local | cut -f2" r]
    set host [lindex [split [read $f] \n] 0]
    close $f
} elseif {[string match -nocase cpe* $num]} {
    set host $num
}

system sed -i -e "s/^sam$num.*//" ~/.ssh/known_hosts
eval spawn scp [glob *.ko] root@$host:/home/root
set timeout $delay
while 1 {
    expect {
        -re {.*word:.*} {
            send "shoot\r"
        }
        -re {.*yes/no.*} {
            send "yes\r"
        }
        eof {
            break
        }
    }
}
