#ifndef __DEFAULTS_H__
#define __DEFAULTS_H

// Hit calibration defaults
#define HIT_MSECS_BETWEEN 100
#define HIT_MSECS_BETWEEN_LOC 0x100
#define HIT_MSECS_BETWEEN_SIZE 0x08

#define HIT_DESENSITIVITY 3
#define HIT_DESENSITIVITY_LOC 0x108
#define HIT_DESENSITIVITY_SIZE 0x08

#define HIT_START_BLANKING 7
#define HIT_START_BLANKING_LOC 0x110
#define HIT_START_BLANKING_SIZE 0x08

#define HIT_ENABLE_ON 4
#define HIT_ENABLE_ON_LOC 0x118
#define HIT_ENABLE_ON_SIZE 0x08

// Hit sensor defaults
#define HIT_SENSOR_TYPE 0
#define HIT_SENSOR_TYPE_LOC 0x120
#define HIT_SENSOR_TYPE_SIZE 0x08

#define HIT_SENSOR_INVERT 0
#define HIT_SENSOR_INVERT_LOC 0x128
#define HIT_SENSOR_INVERT_SIZE 0x08

// Fall Reaction defaults
#define FALL_KILL_AT_X_HITS 1
#define FALL_KILL_AT_X_HITS_LOC 0x2C0
#define FALL_KILL_AT_X_HITS_SIZE 0x20

#define FALL_AT_FALL 3
#define FALL_AT_FALL_LOC 0x2E0
#define FALL_AT_FALL_SIZE 0x20

// Bob type defaults
#define BOB_TYPE 1
#define BOB_TYPE_LOC 0X460
#define BOB_TYPE_SIZE 0X10

// Serial Number defaults
#define SERIAL_NUMBER "00000-0-0"
#define SERIAL_NUMBER_LOC 0x2A0
#define SERIAL_NUMBER_SIZE 0x20

#define SERIAL_SIZE 20

// Address Defaults
#define ADDRESS_LOC 0x280
#define ADDRESS_SIZE 0x20

#define ADD_SIZE 20

// Board Defaults
#define BOARD_LOC 0x00
#define BOARD_SIZE 0x40

#define B_SIZE 40

// Connect Port Defaults
#define CONNECT_PORT_LOC 0x240
#define CONNECT_PORT_SIZE 0x40

#define CONNECT_SIZE 40

// Communication Defaults
#define COMMUNICATION_LOC 0x80
#define COMMUNICATION_SIZE 0x40

#define COMM_SIZE 40

// IP Address Defaults
#define IP_ADDRESS_LOC 0xC0
#define IP_ADDRESS_SIZE 0x40

#define IP_SIZE 40

// Listen Port Defaults
#define LISTEN_PORT_LOC 0x200
#define LISTEN_PORT_SIZE 0x40

#define LISTEN_SIZE 40

// MAC Address Defaults
#define MAC_ADDRESS_LOC 0x40
#define MAC_ADDRESS_SIZE 0x40

#define MAC_SIZE 40

// Battery defaults
#define SIT_BATTERY 12
#define SIT_BATTERY_LOC 0x400
#define SIT_BATTERY_SIZE 0x08

#define SAT_BATTERY 12
#define SAT_BATTERY_LOC 0x408
#define SAT_BATTERY_SIZE 0x08

#define SES_BATTERY 12
#define SES_BATTERY_LOC 0x410
#define SES_BATTERY_SIZE 0x08

#define MIT_BATTERY 48
#define MIT_BATTERY_LOC 0x418
#define MIT_BATTERY_SIZE 0x08

#define MAT_BATTERY 48
#define MAT_BATTERY_LOC 0x420
#define MAT_BATTERY_SIZE 0x08

#define REVERSE 0
#define REVERSE_LOC 0x438
#define REVERSE_SIZE 0x04

#define BATTERY_SIZE 8
#define MOVER_SIZE 4

// SES defaults
#define SES_LOOP 1
#define SES_LOOP_LOC 0x440
#define SES_LOOP_SIZE 0x10

#define SES_MODE 0
#define SES_MODE_LOC 0x450
#define SES_MODE_SIZE 0x10

#define SES_SIZE 10

// MFS defaults (Muzzle Flash Simulator)
#define MFS_EXISTS 1
#define MFS_EXISTS_LOC 0x180
#define MFS_EXISTS_SIZE 0x04

#define MFS_ACTIVATE 0
#define MFS_ACTIVATE_LOC 0x184
#define MFS_ACTIVATE_SIZE 0x04

#define MFS_ACTIVATE_EXPOSE 0
#define MFS_ACTIVATE_EXPOSE_LOC 0x188
#define MFS_ACTIVATE_EXPOSE_SIZE 0x04

#define MFS_ACTIVATE_ON_HIT 0
#define MFS_ACTIVATE_ON_HIT_LOC 0x18C
#define MFS_ACTIVATE_ON_HIT_SIZE 0x04

#define MFS_ACTIVATE_ON_KILL 0
#define MFS_ACTIVATE_ON_KILL_LOC 0x190
#define MFS_ACTIVATE_ON_KILL_SIZE 0x04

#define MFS_MS_ON_TIME 0
#define MFS_MS_ON_TIME_LOC 0x194
#define MFS_MS_ON_TIME_SIZE 0x04

#define MFS_MS_OFF_TIME 0
#define MFS_MS_OFF_TIME_LOC 0x198
#define MFS_MS_OFF_TIME_SIZE 0x04

#define MFS_START_DELAY 1
#define MFS_START_DELAY_LOC 0x19C
#define MFS_START_DELAY_SIZE 0x04

#define MFS_REPEAT_DELAY 5
#define MFS_REPEAT_DELAY_LOC 0x1A0
#define MFS_REPEAT_DELAY_SIZE 0x04

#define MFS_REPEAT_COUNT 0
#define MFS_REPEAT_COUNT_LOC 0x1A4
#define MFS_REPEAT_COUNT_SIZE 0x04

#define MFS_EX1 0
#define MFS_EX1_LOC 0x1A8
#define MFS_EX1_SIZE 0x04	

#define MFS_EX2 0
#define MFS_EX2_LOC 0x1AC
#define MFS_EX2_SIZE 0x04

#define MFS_EX3 0
#define MFS_EX3_LOC 0x1B0
#define MFS_EX3_SIZE 0x04

#define MFS_MODE 0
#define MFS_MODE_LOC 0x1B4
#define MFS_MODE_SIZE 0x04

#define MFS_SIZE 4

// MGL defaults (Moon Glow Simulator)
#define MGL_EXISTS 1
#define MGL_EXISTS_LOC 0x340
#define MGL_EXISTS_SIZE 0x04

#define MGL_ACTIVATE 0
#define MGL_ACTIVATE_LOC 0x344
#define MGL_ACTIVATE_SIZE 0x04

#define MGL_ACTIVATE_EXPOSE 0
#define MGL_ACTIVATE_EXPOSE_LOC 0x348
#define MGL_ACTIVATE_EXPOSE_SIZE 0x04

#define MGL_ACTIVATE_ON_HIT 0
#define MGL_ACTIVATE_ON_HIT_LOC 0x34C
#define MGL_ACTIVATE_ON_HIT_SIZE 0x04

#define MGL_ACTIVATE_ON_KILL 0
#define MGL_ACTIVATE_ON_KILL_LOC 0x350
#define MGL_ACTIVATE_ON_KILL_SIZE 0x04

#define MGL_MS_ON_TIME 0
#define MGL_MS_ON_TIME_LOC 0x354
#define MGL_MS_ON_TIME_SIZE 0x04

#define MGL_MS_OFF_TIME 0
#define MGL_MS_OFF_TIME_LOC 0x358
#define MGL_MS_OFF_TIME_SIZE 0x04

#define MGL_START_DELAY 0
#define MGL_START_DELAY_LOC 0x35C
#define MGL_START_DELAY_SIZE 0x04

#define MGL_REPEAT_DELAY 0
#define MGL_REPEAT_DELAY_LOC 0x360
#define MGL_REPEAT_DELAY_SIZE 0x04

#define MGL_REPEAT_COUNT 0
#define MGL_REPEAT_COUNT_LOC 0x364
#define MGL_REPEAT_COUNT_SIZE 0x04

#define MGL_EX1 0
#define MGL_EX1_LOC 0x368
#define MGL_EX1_SIZE 0x04	

#define MGL_EX2 0
#define MGL_EX2_LOC 0x36C
#define MGL_EX2_SIZE 0x04

#define MGL_EX3 0
#define MGL_EX3_LOC 0x370
#define MGL_EX3_SIZE 0x04

#define MGL_SIZE 4

// PHI defaults (Positive Hit Indicator)
#define PHI_EXISTS 1
#define PHI_EXISTS_LOC 0x380
#define PHI_EXISTS_SIZE 0x04

#define PHI_ACTIVATE 0
#define PHI_ACTIVATE_LOC 0x384
#define PHI_ACTIVATE_SIZE 0x04

#define PHI_ACTIVATE_EXPOSE 0
#define PHI_ACTIVATE_EXPOSE_LOC 0x388
#define PHI_ACTIVATE_EXPOSE_SIZE 0x04

#define PHI_ACTIVATE_ON_HIT 0
#define PHI_ACTIVATE_ON_HIT_LOC 0x38C
#define PHI_ACTIVATE_ON_HIT_SIZE 0x04

#define PHI_ACTIVATE_ON_KILL 0
#define PHI_ACTIVATE_ON_KILL_LOC 0x390
#define PHI_ACTIVATE_ON_KILL_SIZE 0x04

#define PHI_MS_ON_TIME 2000
#define PHI_MS_ON_TIME_LOC 0x394
#define PHI_MS_ON_TIME_SIZE 0x04

#define PHI_MS_OFF_TIME 0
#define PHI_MS_OFF_TIME_LOC 0x398
#define PHI_MS_OFF_TIME_SIZE 0x04

#define PHI_START_DELAY 0
#define PHI_START_DELAY_LOC 0x39C
#define PHI_START_DELAY_SIZE 0x04

#define PHI_REPEAT_DELAY 0
#define PHI_REPEAT_DELAY_LOC 0x3A0
#define PHI_REPEAT_DELAY_SIZE 0x04

#define PHI_REPEAT_COUNT 0
#define PHI_REPEAT_COUNT_LOC 0x3A4
#define PHI_REPEAT_COUNT_SIZE 0x04

#define PHI_EX1 0
#define PHI_EX1_LOC 0x3A8
#define PHI_EX1_SIZE 0x04

#define PHI_EX2 0
#define PHI_EX2_LOC 0x3AC
#define PHI_EX2_SIZE 0x04

#define PHI_EX3 0
#define PHI_EX3_LOC 0x3B0
#define PHI_EX3_SIZE 0x04

#define PHI_SIZE 4

// SMK defaults (Smoke)
#define SMK_EXISTS 0
#define SMK_EXISTS_LOC 0x300
#define SMK_EXISTS_SIZE 0x04

#define SMK_ACTIVATE 0
#define SMK_ACTIVATE_LOC 0x304
#define SMK_ACTIVATE_SIZE 0x04

#define SMK_ACTIVATE_EXPOSE 0
#define SMK_ACTIVATE_EXPOSE_LOC 0x308
#define SMK_ACTIVATE_EXPOSE_SIZE 0x04

#define SMK_ACTIVATE_ON_HIT 0
#define SMK_ACTIVATE_ON_HIT_LOC 0x30C
#define SMK_ACTIVATE_ON_HIT_SIZE 0x04

#define SMK_ACTIVATE_ON_KILL 0
#define SMK_ACTIVATE_ON_KILL_LOC 0x310
#define SMK_ACTIVATE_ON_KILL_SIZE 0x04

#define SMK_MS_ON_TIME 0
#define SMK_MS_ON_TIME_LOC 0x314
#define SMK_MS_ON_TIME_SIZE 0x04

#define SMK_MS_OFF_TIME 0
#define SMK_MS_OFF_TIME_LOC 0x318
#define SMK_MS_OFF_TIME_SIZE 0x04

#define SMK_START_DELAY 0
#define SMK_START_DELAY_LOC 0x31C
#define SMK_START_DELAY_SIZE 0x04

#define SMK_REPEAT_DELAY 0
#define SMK_REPEAT_DELAY_LOC 0x320
#define SMK_REPEAT_DELAY_SIZE 0x04

#define SMK_REPEAT_COUNT 0
#define SMK_REPEAT_COUNT_LOC 0x324
#define SMK_REPEAT_COUNT_SIZE 0x04

#define SMK_EX1 0
#define SMK_EX1_LOC 0x328
#define SMK_EX1_SIZE 0x04	

#define SMK_EX2 0
#define SMK_EX2_LOC 0x32C
#define SMK_EX2_SIZE 0x04

#define SMK_EX3 0
#define SMK_EX3_LOC 0x330
#define SMK_EX3_SIZE 0x04

#define SMK_SIZE 4

// THM defaults (Thermals)
#define THM_EXISTS 0
#define THM_EXISTS_LOC 0x3C0
#define THM_EXISTS_SIZE 0x04

#define THM_ACTIVATE 0
#define THM_ACTIVATE_LOC 0x3C4
#define THM_ACTIVATE_SIZE 0x04

#define THM_ACTIVATE_EXPOSE 0
#define THM_ACTIVATE_EXPOSE_LOC 0x3C8
#define THM_ACTIVATE_EXPOSE_SIZE 0x04

#define THM_ACTIVATE_ON_HIT 0
#define THM_ACTIVATE_ON_HIT_LOC 0x3CC
#define THM_ACTIVATE_ON_HIT_SIZE 0x04

#define THM_ACTIVATE_ON_KILL 0
#define THM_ACTIVATE_ON_KILL_LOC 0x3D0
#define THM_ACTIVATE_ON_KILL_SIZE 0x04

#define THM_MS_ON_TIME 0
#define THM_MS_ON_TIME_LOC 0x3D4
#define THM_MS_ON_TIME_SIZE 0x04

#define THM_MS_OFF_TIME 0
#define THM_MS_OFF_TIME_LOC 0x3D8
#define THM_MS_OFF_TIME_SIZE 0x04

#define THM_START_DELAY 0
#define THM_START_DELAY_LOC 0x3DC
#define THM_START_DELAY_SIZE 0x04

#define THM_REPEAT_DELAY 0
#define THM_REPEAT_DELAY_LOC 0x3E0
#define THM_REPEAT_DELAY_SIZE 0x04

#define THM_REPEAT_COUNT 0
#define THM_REPEAT_COUNT_LOC 0x3E4
#define THM_REPEAT_COUNT_SIZE 0x04

#define THM_EX1 0
#define THM_EX1_LOC 0x3E8
#define THM_EX1_SIZE 0x04	

#define THM_EX2 0
#define THM_EX2_LOC 0x3EC
#define THM_EX2_SIZE 0x04

#define THM_EX3 0
#define THM_EX3_LOC 0x3F0
#define THM_EX3_SIZE 0x04

#define THM_SIZE 4

// MSD defaults (Miles Shootback Device)
#define MSD_EXISTS 0
#define MSD_EXISTS_LOC 0x143
#define MSD_EXISTS_SIZE 0x04

#define MSD_ACTIVATE 0
#define MSD_ACTIVATE_LOC 0x147
#define MSD_ACTIVATE_SIZE 0x04

#define MSD_ACTIVATE_EXPOSE 2
#define MSD_ACTIVATE_EXPOSE_LOC 0x14B
#define MSD_ACTIVATE_EXPOSE_SIZE 0x04

#define MSD_ACTIVATE_ON_HIT 0
#define MSD_ACTIVATE_ON_HIT_LOC 0x14F
#define MSD_ACTIVATE_ON_HIT_SIZE 0x04

#define MSD_ACTIVATE_ON_KILL 2
#define MSD_ACTIVATE_ON_KILL_LOC 0x153
#define MSD_ACTIVATE_ON_KILL_SIZE 0x04

#define MSD_MS_ON_TIME 0
#define MSD_MS_ON_TIME_LOC 0x157
#define MSD_MS_ON_TIME_SIZE 0x04

#define MSD_MS_OFF_TIME 0
#define MSD_MS_OFF_TIME_LOC 0x15B
#define MSD_MS_OFF_TIME_SIZE 0x04

#define MSD_START_DELAY 0
#define MSD_START_DELAY_LOC 0x15F
#define MSD_START_DELAY_SIZE 0x04

#define MSD_REPEAT_DELAY 0
#define MSD_REPEAT_DELAY_LOC 0x163
#define MSD_REPEAT_DELAY_SIZE 0x04

#define MSD_REPEAT_COUNT 0
#define MSD_REPEAT_COUNT_LOC 0x167
#define MSD_REPEAT_COUNT_SIZE 0x04

#define MSD_EX1 1
#define MSD_EX1_LOC 0x16B
#define MSD_EX1_SIZE 0x04	

#define MSD_EX2 00
#define MSD_EX2_LOC 0x16F
#define MSD_EX2_SIZE 0x04

#define MSD_EX3 00
#define MSD_EX3_LOC 0x173
#define MSD_EX3_SIZE 0x04

#define MSD_SIZE 4

// radio defaults
#define RADIO_FREQ "405.000"
#define RADIO_FREQ_LOC 0x500
#define RADIO_FREQ_SIZE 0x4f

#define RADIO_POWER_L 1
#define RADIO_POWER_L_LOC 0x550
#define RADIO_POWER_L_SIZE 0x4

#define RADIO_POWER_H 25
#define RADIO_POWER_H_LOC 0x554
#define RADIO_POWER_H_SIZE 0x4

#define RADIO_WRITTEN "N"
#define RADIO_WRITTEN_LOC 0x558
#define RADIO_WRITTEN_SIZE 0x4

// docking defaults
#define DOCKING_END 0
#define DOCKING_END_LOC 0x55C
#define DOCKING_END_SIZE 0x4

// home end defaults
#define HOME_END 0
#define HOME_END_LOC 0x560
#define HOME_END_SIZE 0x4

// Flash Version
#define VERSION "00000000" /* format: YYYYMMDD */
#define VERSION_LOC 0x564
#define VERSION_SIZE 0x10


// Mover track length
#define TRACK_LENGTH 5
#define TRACK_LENGTH_LOC 0x574
#define TRACK_LENGTH_SIZE 0x4

// Static IP Address for movers
#define STATIC_IP "0.0.0.0"
#define STATIC_IP_LOC 0x578
#define STATIC_IP_SIZE 0x20

// BT1 defaults (BES Trigger 1)
#define BT1_EXISTS 0
#define BT1_EXISTS_LOC 0x600
#define BT1_EXISTS_SIZE 0x04

#define BT1_ACTIVATE 0
#define BT1_ACTIVATE_LOC 0x604
#define BT1_ACTIVATE_SIZE 0x04

#define BT1_ACTIVATE_EXPOSE 0
#define BT1_ACTIVATE_EXPOSE_LOC 0x608
#define BT1_ACTIVATE_EXPOSE_SIZE 0x04

#define BT1_ACTIVATE_ON_HIT 0
#define BT1_ACTIVATE_ON_HIT_LOC 0x60C
#define BT1_ACTIVATE_ON_HIT_SIZE 0x04

#define BT1_ACTIVATE_ON_KILL 0
#define BT1_ACTIVATE_ON_KILL_LOC 0x610
#define BT1_ACTIVATE_ON_KILL_SIZE 0x04

#define BT1_MS_ON_TIME 0
#define BT1_MS_ON_TIME_LOC 0x614
#define BT1_MS_ON_TIME_SIZE 0x04

#define BT1_MS_OFF_TIME 0
#define BT1_MS_OFF_TIME_LOC 0x618
#define BT1_MS_OFF_TIME_SIZE 0x04

#define BT1_START_DELAY 0
#define BT1_START_DELAY_LOC 0x61C
#define BT1_START_DELAY_SIZE 0x04

#define BT1_REPEAT_DELAY 0
#define BT1_REPEAT_DELAY_LOC 0x620
#define BT1_REPEAT_DELAY_SIZE 0x04

#define BT1_REPEAT_COUNT 0
#define BT1_REPEAT_COUNT_LOC 0x624
#define BT1_REPEAT_COUNT_SIZE 0x04

#define BT1_EX1 0
#define BT1_EX1_LOC 0x628
#define BT1_EX1_SIZE 0x04	

#define BT1_EX2 0
#define BT1_EX2_LOC 0x62C
#define BT1_EX2_SIZE 0x04

#define BT1_EX3 0
#define BT1_EX3_LOC 0x630
#define BT1_EX3_SIZE 0x04

#define BT1_SIZE 4

// BT2 defaults (BES Trigger 2)
#define BT2_EXISTS 0
#define BT2_EXISTS_LOC 0x640
#define BT2_EXISTS_SIZE 0x04

#define BT2_ACTIVATE 0
#define BT2_ACTIVATE_LOC 0x644
#define BT2_ACTIVATE_SIZE 0x04

#define BT2_ACTIVATE_EXPOSE 0
#define BT2_ACTIVATE_EXPOSE_LOC 0x648
#define BT2_ACTIVATE_EXPOSE_SIZE 0x04

#define BT2_ACTIVATE_ON_HIT 0
#define BT2_ACTIVATE_ON_HIT_LOC 0x64C
#define BT2_ACTIVATE_ON_HIT_SIZE 0x04

#define BT2_ACTIVATE_ON_KILL 0
#define BT2_ACTIVATE_ON_KILL_LOC 0x650
#define BT2_ACTIVATE_ON_KILL_SIZE 0x04

#define BT2_MS_ON_TIME 0
#define BT2_MS_ON_TIME_LOC 0x654
#define BT2_MS_ON_TIME_SIZE 0x04

#define BT2_MS_OFF_TIME 0
#define BT2_MS_OFF_TIME_LOC 0x658
#define BT2_MS_OFF_TIME_SIZE 0x04

#define BT2_START_DELAY 0
#define BT2_START_DELAY_LOC 0x65C
#define BT2_START_DELAY_SIZE 0x04

#define BT2_REPEAT_DELAY 0
#define BT2_REPEAT_DELAY_LOC 0x660
#define BT2_REPEAT_DELAY_SIZE 0x04

#define BT2_REPEAT_COUNT 0
#define BT2_REPEAT_COUNT_LOC 0x664
#define BT2_REPEAT_COUNT_SIZE 0x04

#define BT2_EX1 0
#define BT2_EX1_LOC 0x668
#define BT2_EX1_SIZE 0x04	

#define BT2_EX2 0
#define BT2_EX2_LOC 0x66C
#define BT2_EX2_SIZE 0x04

#define BT2_EX3 0
#define BT2_EX3_LOC 0x670
#define BT2_EX3_SIZE 0x04

#define BT2_SIZE 4

// BT3 defaults (BES Trigger 3)
#define BT3_EXISTS 0
#define BT3_EXISTS_LOC 0x680
#define BT3_EXISTS_SIZE 0x04

#define BT3_ACTIVATE 0
#define BT3_ACTIVATE_LOC 0x684
#define BT3_ACTIVATE_SIZE 0x04

#define BT3_ACTIVATE_EXPOSE 0
#define BT3_ACTIVATE_EXPOSE_LOC 0x688
#define BT3_ACTIVATE_EXPOSE_SIZE 0x04

#define BT3_ACTIVATE_ON_HIT 0
#define BT3_ACTIVATE_ON_HIT_LOC 0x68C
#define BT3_ACTIVATE_ON_HIT_SIZE 0x04

#define BT3_ACTIVATE_ON_KILL 0
#define BT3_ACTIVATE_ON_KILL_LOC 0x690
#define BT3_ACTIVATE_ON_KILL_SIZE 0x04

#define BT3_MS_ON_TIME 0
#define BT3_MS_ON_TIME_LOC 0x694
#define BT3_MS_ON_TIME_SIZE 0x04

#define BT3_MS_OFF_TIME 0
#define BT3_MS_OFF_TIME_LOC 0x698
#define BT3_MS_OFF_TIME_SIZE 0x04

#define BT3_START_DELAY 0
#define BT3_START_DELAY_LOC 0x69C
#define BT3_START_DELAY_SIZE 0x04

#define BT3_REPEAT_DELAY 0
#define BT3_REPEAT_DELAY_LOC 0x6A0
#define BT3_REPEAT_DELAY_SIZE 0x04

#define BT3_REPEAT_COUNT 0
#define BT3_REPEAT_COUNT_LOC 0x6A4
#define BT3_REPEAT_COUNT_SIZE 0x04

#define BT3_EX1 0
#define BT3_EX1_LOC 0x6A8
#define BT3_EX1_SIZE 0x04	

#define BT3_EX2 0
#define BT3_EX2_LOC 0x6AC
#define BT3_EX2_SIZE 0x04

#define BT3_EX3 0
#define BT3_EX3_LOC 0x6B0
#define BT3_EX3_SIZE 0x04

#define BT3_SIZE 4

// BT4 defaults (BES Trigger 4)
#define BT4_EXISTS 0
#define BT4_EXISTS_LOC 0x6C0
#define BT4_EXISTS_SIZE 0x04

#define BT4_ACTIVATE 0
#define BT4_ACTIVATE_LOC 0x6C4
#define BT4_ACTIVATE_SIZE 0x04

#define BT4_ACTIVATE_EXPOSE 0
#define BT4_ACTIVATE_EXPOSE_LOC 0x6C8
#define BT4_ACTIVATE_EXPOSE_SIZE 0x04

#define BT4_ACTIVATE_ON_HIT 0
#define BT4_ACTIVATE_ON_HIT_LOC 0x6CC
#define BT4_ACTIVATE_ON_HIT_SIZE 0x04

#define BT4_ACTIVATE_ON_KILL 0
#define BT4_ACTIVATE_ON_KILL_LOC 0x6D0
#define BT4_ACTIVATE_ON_KILL_SIZE 0x04

#define BT4_MS_ON_TIME 0
#define BT4_MS_ON_TIME_LOC 0x6D4
#define BT4_MS_ON_TIME_SIZE 0x04

#define BT4_MS_OFF_TIME 0
#define BT4_MS_OFF_TIME_LOC 0x6D8
#define BT4_MS_OFF_TIME_SIZE 0x04

#define BT4_START_DELAY 0
#define BT4_START_DELAY_LOC 0x6DC
#define BT4_START_DELAY_SIZE 0x04

#define BT4_REPEAT_DELAY 0
#define BT4_REPEAT_DELAY_LOC 0x6E0
#define BT4_REPEAT_DELAY_SIZE 0x04

#define BT4_REPEAT_COUNT 0
#define BT4_REPEAT_COUNT_LOC 0x6E4
#define BT4_REPEAT_COUNT_SIZE 0x04

#define BT4_EX1 0
#define BT4_EX1_LOC 0x6E8
#define BT4_EX1_SIZE 0x04	

#define BT4_EX2 0
#define BT4_EX2_LOC 0x6EC
#define BT4_EX2_SIZE 0x04

#define BT4_EX3 0
#define BT4_EX3_LOC 0x6F0
#define BT4_EX3_SIZE 0x04

#define BT4_SIZE 4
// ,.. defaults


#endif
